analytics: {}
color:
  brandColors:
    - '#CA2F11'
    - '#DFDBD2'
    - '#1B0B0E'
    - '#B39579'
    - '#1F20AE'
  brandStrength: 0.954955
  lightness: 0.644144
  rhythmicContrast: 0.766891
  saturation: 0.552927
cta: {}
layout_spectrum: 0.534030425191157
name: WORDS we SPELL
opengraph: {}
purpose: {}
typography_spectrum: 0
