analytics: {}
color:
  brandColors:
    - '#DACAA9'
    - '#1D0B07'
    - '#C8AE40'
    - '#764C1A'
    - '#CA8160'
  brandStrength: 0.251126
  lightness: 0.644144
  rhythmicContrast: 0.849099
  saturation: 0.761261
cta: {}
layout_spectrum: 0.70045
name: WORDS we SPELL
opengraph: {}
purpose: {}
typography_spectrum: 0
