analytics: {}
color:
  brandColors:
    - '#DACAA9'
    - '#1D0B07'
    - '#C8AE40'
    - '#764C1A'
    - '#CA8160'
  brandStrength: 0.80518
  lightness: 0.757882
  rhythmicContrast: 0.048423
  saturation: 0.789414
cta: {}
layout_spectrum: 0.789414
name: WORDS we SPELL
opengraph: {}
purpose: {}
typography_spectrum: 0
