analytics: {}
color:
  brandColors:
    - '#DACAA9'
    - '#1D0B07'
    - '#C8AE40'
    - '#764C1A'
    - '#CA8160'
  brandStrength: 0
  lightness: 0.757882
  rhythmicContrast: 0.671171
  saturation: 1
cta: {}
layout_spectrum: 0.70045
name: WORDS we SPELL
opengraph: {}
purpose: {}
typography_spectrum: 0
