analytics: {}
color:
  brandColors:
    - '#B2B4B3'
    - '#D7D6D1'
    - '#BEAB28'
    - '#97680E'
    - '#F9F379'
  brandStrength: 0.751126
  lightness: 0.558558
  rhythmicContrast: 0
  saturation: 1
cta: {}
layout_spectrum: 0.789414
name: WORDS we SPELL
opengraph: {}
purpose: {}
typography_spectrum: 0
